### ISSUE TITLE
Find a way to deal with intentional abuse

### ISSUE THREAD

**Issue by winsmith** [mxsasha/happinesspackets#19]
Right now, the only way for the project to deal with targeted abuse (e.g. the gamerg__te kind) is for the person being harassed to  put the themslves onto a blacklist. This is a good start, but I would like to start a discussion on what else we could do. Here are some options. 
## Collate emails

Example: an imageboard has just discovered a target they want to harass and begins a large scale operation using happiness packets. The target is in a position where she or he cannot read their email for an hour. Next thing, their email account is completely filled with emails full of hate. 

To prevent this, we could only send out _n_ emails to one person, followed by "if you want to receive more such packets, please click this link". 

Even after they agreed to get emails, they could get overwhelmed later on. This could be mitigated by holding on to messages for 24 hours and then sending them as one email.
## Throttle Email Senders

A person sending out happiness packets should only be able to send out _n_ packets per 24 hour period. 
## Shadow Banning

Instead of telling a person that their email is banned from sending any new happiness packets, accept and then immediately discard their packets. This will prevent some of them from realizing the ban and switching discardable email addresses to circumvent that. 
## Blocking

Recipients should be able to block specific email addresses from sending them packets. If a user is blocked by too many recipients, they should get (shadow) banned.  

I'd like to hear about other ideas on how to prevent abuse, and I'm very willing to help implement them as well. I want the happiness packets to be a source of happiness, not something everyone will spamblock. Thanks :)

**Comment by winsmith** [comment]
Right now, the only way for the project to deal with targeted abuse (e.g. the gamerg__te kind) is for the person being harassed to  put the themslves onto a blacklist. This is a good start, but I would like to start a discussion on what else we could do. Here are some options. 

## Collate emails
Example: an imageboard has just discovered a target they want to harass and begins a large scale operation using happiness packets. The target is in a position where she or he cannot read their email for an hour. Next thing, their email account is completely filled with emails full of hate. 

To prevent this, we could only send out *n* emails to one person, followed by "if you want to receive more such packets, please click this link". 

Even after they agreed to get emails, they could get overwhelmed later on. This could be mitigated by holding on to messages for 24 hours and then sending them as one email.

## Throttle Email Senders
A person sending out happiness packets should only be able to send out *n* packets per 24 hour period. 

## Shadow Banning
Instead of telling a person that their email is banned from sending any new happiness packets, accept and then immediately discard their packets. This will prevent some of them from realizing the ban and switching discardable email addresses to circumvent that. 

## Blocking 
Recipients should be able to block specific email addresses from sending them packets. If a user is blocked by too many recipients, they should get (shadow) banned.  

I'd like to hear about other ideas on how to prevent abuse, and I'm very willing to help implement them as well. I want the happiness packets to be a source of happiness, not something everyone will spamblock. Thanks :)

**Comment by erikr** [comment]
Thanks for those suggestions. I just implemented the shadowbanning for cases where someone asked to blacklist their e-mail. The other ideas that I think are most practical now is limiting the number of outgoing emails per recipient without further confirmation, and perhaps limiting the number of messages per IP address?
