### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by Algogator** [mxsasha/happinesspackets#35]
https://paste.fedoraproject.org/paste/NYgrbTqnAEHk9uSeewSMxg

> IOError: [Errno 2] No such file or directory: Path('/home/anna/Projects/happinesspackets/static/images/logo.png')

**Comment by mxsasha** [comment]
Thanks for the report. Some of the email rendering code depends on loading the logo from the configured STATIC_FILES dir, so before running the tests you'd have to run `./manage.py collectstatic`. After doing that, the tests work for me.
